<?php
/**
 * Google Tag Manager Template
 *
 * @category    KL
 * @package     KL_GoogleTagManager
 * @since       0.1.0.0
 * @author      Erik Eng <erik@karlssonlord.com>
 *
 */
?>
<?php if($this->getContainerId()) : ?>
    <!-- Google Tag Manager -->
    <?php if($this->getDataLayer()) : ?>
        <script>dataLayer = [<?php echo Zend_Json::encode($this->getDataLayer()); ?>];</script>
    <?php endif; ?>

    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $this->getContainerId(); ?>"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php echo $this->getContainerId(); ?>');</script>
    <!-- End Google Tag Manager -->
<?php endif; ?>